In [4]:
import numpy as np

In [5]:
arr1=np.array([[8,0,3],[90,87,3],[90,45,3]])

In [10]:
print(arr1)
det_mat=np.linalg.det(arr1)


[[ 8  0  3]
 [90 87  3]
 [90 45  3]]


In [13]:
det_mat

-10332.000000000002

In [20]:
inverse=np.linalg.inv(arr1)


In [21]:
inverse

array([[-0.01219512, -0.0130662 ,  0.02526132],
       [-0.        ,  0.02380952, -0.02380952],
       [ 0.36585366,  0.03484321, -0.06736353]])

In [23]:
Dense=np.array([[1,0,3,0],[0,0,0,6],[0,5,6,7],[0,6,0,9]])

In [24]:
Dense

array([[1, 0, 3, 0],
       [0, 0, 0, 6],
       [0, 5, 6, 7],
       [0, 6, 0, 9]])

In [25]:
from scipy.sparse import csr_matrix

In [ ]:
spar