In [2]:
import numpy as np

In [3]:
ar1=np.array(6)

In [4]:
ar1

array(6)

In [24]:
ar2=np.array([[2,3,4,5,6],[1,2,3,4,5]])

In [25]:
ar2

array([[2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5]])

In [26]:
ar3=np.array([[1,2,3,4],[2,3,4,5]])

In [27]:
ar3

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [7]:
zero_array=np.zeros((2,2))

In [8]:
zero_array

array([0., 0.])

In [10]:
one_array=np.ones((2,2))

In [11]:
one_array

array([[1., 1.],
       [1., 1.]])

In [19]:
ar4=np.arange(2,15,3)

In [20]:
ar4

array([ 2,  5,  8, 11, 14])

In [28]:
ar5=np.transpose(ar3)

In [29]:
ar5

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

In [31]:
ar6=np.ravel(ar5)

In [32]:
ar6

array([1, 2, 2, 3, 3, 4, 4, 5])

In [33]:
a1=np.array([2,2])
a2=np.array([4,2])

In [34]:
a1

array([2, 2])

In [36]:
concat=np.concatenate((a1,a2))


In [37]:
concat

array([2, 2, 4, 2])

In [38]:
hori=np.hstack((a1,a2))

In [39]:
hori

array([2, 2, 4, 2])