In [ ]:
#machine learning -supervised learning
1.regression
2.classification

# 

# importing library

In [3]:
import numpy as np
import pandas as pd

C:\Users\SN113\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [4]:
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
#import data set

In [6]:
har=pd.read_csv("Admission_Predict.csv")

In [7]:
print(har)

     Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

    Research  Chance of Admit   
0        Yes      

In [9]:
har2=har.drop(['Serial No.','GRE Score','TOEFL Score','University Rating','SOP','LOR ','Research'], axis=1)

In [10]:
har2

CGPA  Chance of Admit 
0    9.65              0.92
1    8.87              0.76
2    8.00              0.72
3    8.67              0.80
4    8.21              0.65
..    ...               ...
395  9.04              0.82
396  9.11              0.84
397  9.45              0.91
398  8.78              0.67
399  9.66              0.95

[400 rows x 2 columns]

In [23]:
x=har2.iloc[:,0].values.reshape(-1,1)
y=har2.iloc[:,1].values.reshape(-1,1)

In [24]:
x

array([[9.65],
       [8.87],
       [8.  ],
       [8.67],
       [8.21],
       [9.34],
       [8.2 ],
       [7.9 ],
       [8.  ],
       [8.6 ],
       [8.4 ],
       [9.  ],
       [9.1 ],
       [8.  ],
       [8.2 ],
       [8.3 ],
       [8.7 ],
       [8.  ],
       [8.8 ],
       [8.5 ],
       [7.9 ],
       [8.4 ],
       [9.5 ],
       [9.7 ],
       [9.8 ],
       [9.6 ],
       [8.8 ],
       [7.5 ],
       [7.2 ],
       [7.3 ],
       [8.1 ],
       [8.3 ],
       [9.4 ],
       [9.6 ],
       [9.8 ],
       [9.2 ],
       [8.4 ],
       [7.8 ],
       [7.5 ],
       [7.7 ],
       [8.  ],
       [8.2 ],
       [8.5 ],
       [9.1 ],
       [9.4 ],
       [9.1 ],
       [9.3 ],
       [9.7 ],
       [8.85],
       [8.4 ],
       [8.3 ],
       [7.9 ],
       [8.  ],
       [8.1 ],
       [8.  ],
       [7.7 ],
       [7.4 ],
       [7.6 ],
       [6.8 ],
       [8.3 ],
       [8.1 ],
       [8.2 ],
       [8.2 ],
       [8.5 ],
       [8.7 ],
       [8.92],
       [9.

In [25]:
y

array([[0.92],
       [0.76],
       [0.72],
       [0.8 ],
       [0.65],
       [0.9 ],
       [0.75],
       [0.68],
       [0.5 ],
       [0.45],
       [0.52],
       [0.84],
       [0.78],
       [0.62],
       [0.61],
       [0.54],
       [0.66],
       [0.65],
       [0.63],
       [0.62],
       [0.64],
       [0.7 ],
       [0.94],
       [0.95],
       [0.97],
       [0.94],
       [0.76],
       [0.44],
       [0.46],
       [0.54],
       [0.65],
       [0.74],
       [0.91],
       [0.9 ],
       [0.94],
       [0.88],
       [0.64],
       [0.58],
       [0.52],
       [0.48],
       [0.46],
       [0.49],
       [0.53],
       [0.87],
       [0.91],
       [0.88],
       [0.86],
       [0.89],
       [0.82],
       [0.78],
       [0.76],
       [0.56],
       [0.78],
       [0.72],
       [0.7 ],
       [0.64],
       [0.64],
       [0.46],
       [0.36],
       [0.42],
       [0.48],
       [0.47],
       [0.54],
       [0.56],
       [0.52],
       [0.55],
       [0.

# splitting the dataset 

In [27]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [28]:
from sklearn.model_selection import train_test_split

In [31]:
x_test=x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [33]:
y_test=y_train,y_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [35]:
y_test

array([[0.71],
       [0.7 ],
       [0.79],
       [0.73],
       [0.72],
       [0.48],
       [0.77],
       [0.71],
       [0.9 ],
       [0.94],
       [0.58],
       [0.89],
       [0.72],
       [0.57],
       [0.78],
       [0.42],
       [0.64],
       [0.84],
       [0.63],
       [0.72],
       [0.9 ],
       [0.83],
       [0.57],
       [0.47],
       [0.85],
       [0.67],
       [0.44],
       [0.54],
       [0.92],
       [0.62],
       [0.68],
       [0.73],
       [0.73],
       [0.61],
       [0.55],
       [0.74],
       [0.64],
       [0.89],
       [0.73],
       [0.95],
       [0.71],
       [0.72],
       [0.75],
       [0.76],
       [0.86],
       [0.7 ],
       [0.39],
       [0.79],
       [0.61],
       [0.64],
       [0.71],
       [0.8 ],
       [0.61],
       [0.89],
       [0.68],
       [0.79],
       [0.78],
       [0.52],
       [0.76],
       [0.88],
       [0.74],
       [0.49],
       [0.65],
       [0.59],
       [0.87],
       [0.89],
       [0.

In [30]:
x_test

array([[8.56],
       [8.6 ],
       [8.76],
       [8.26],
       [8.73],
       [8.1 ],
       [8.69],
       [8.09],
       [9.36],
       [9.42],
       [7.8 ],
       [9.28],
       [8.56],
       [7.25],
       [9.1 ],
       [8.3 ],
       [8.18],
       [9.15],
       [7.89],
       [8.69],
       [9.16],
       [9.14],
       [8.47],
       [7.34],
       [8.87],
       [8.04],
       [7.54],
       [8.3 ],
       [9.19],
       [8.25],
       [8.04],
       [8.55],
       [8.65],
       [8.03],
       [8.92],
       [8.72],
       [7.92],
       [9.23],
       [8.27],
       [9.66],
       [8.46],
       [8.27],
       [8.2 ],
       [8.87],
       [9.11],
       [8.  ],
       [7.65],
       [8.37],
       [8.14],
       [8.07],
       [8.48],
       [8.96],
       [8.32],
       [9.07],
       [8.64],
       [8.8 ],
       [8.  ],
       [8.4 ],
       [8.8 ],
       [9.1 ],
       [8.9 ],
       [7.64],
       [8.21],
       [7.67],
       [8.98],
       [9.22],
       [8.

In [32]:
x_train

array([[8.79],
       [8.7 ],
       [7.7 ],
       [9.18],
       [8.  ],
       [9.01],
       [8.36],
       [8.54],
       [9.04],
       [9.14],
       [8.84],
       [9.68],
       [7.4 ],
       [8.  ],
       [9.16],
       [8.48],
       [8.77],
       [8.24],
       [8.76],
       [8.9 ],
       [8.57],
       [8.5 ],
       [9.  ],
       [7.9 ],
       [8.9 ],
       [8.46],
       [9.5 ],
       [8.04],
       [8.75],
       [8.57],
       [8.  ],
       [8.76],
       [8.67],
       [8.4 ],
       [9.17],
       [9.26],
       [9.34],
       [8.4 ],
       [8.37],
       [8.13],
       [8.03],
       [8.45],
       [9.31],
       [8.27],
       [7.56],
       [9.44],
       [9.5 ],
       [8.54],
       [8.27],
       [7.8 ],
       [9.43],
       [8.76],
       [9.02],
       [7.68],
       [8.97],
       [8.12],
       [9.18],
       [8.76],
       [8.02],
       [8.  ],
       [9.01],
       [8.68],
       [8.1 ],
       [8.45],
       [8.79],
       [8.47],
       [7.